<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>InstantInsurance</RootNamespace>
    <Version>1.1.0</Version>
    <Authors>ozen</Authors>
    <AssemblyName>$(Authors).$(RootNamespace)</AssemblyName>
    <RepositoryUrl>https://github.com/ozen-m/SPT-InstantInsurance</RepositoryUrl>
    <DebugType>portable</DebugType>
    <!-- The two lines below will set the output path for the binaries -->
    <OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SPTarkov.Common" Version="4.1.2" />
    <PackageReference Include="SPTarkov.DI" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.1.2" />
    <PackageReference Include="SPTarkov.Server.Web" Version="4.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.*" PrivateAssets="all" />
    <Publicize Include="SPTarkov.Server.Core" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
  </ItemGroup>

  <PropertyGroup>
<!--    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>-->
  </PropertyGroup>

  <Target Name="SetOutput" AfterTargets="Build">
    <PropertyGroup>
      <DestDir>SPT_Runtime\user\mods\$(Authors).$(SolutionName)</DestDir>
    </PropertyGroup>
    <ItemGroup>
      <OutputDLL Include="$(TargetPath)" />
      <OutputDLL Include="$(TargetDir)$(TargetName).pdb" />
      <Config Include="$(TargetDir)\config\**\*" />
    </ItemGroup>
  </Target>
</Project>
